### ISSUE TITLE
How to build tcl script file for yosys systemverilog plugin?

### ISSUE THREAD

**Issue by minghungumich** [chipsalliance/yosys-f4pga-plugins#339]
As #326 points, I can reproduce the systemverilog result in #295 in yosys interactive mode.
If I use the script mode and run the script below `yosys -s script_file`, it can run to the end and output the netlist.
```
plugin -i systemverilog
read_systemverilog $file
synth -top $top_module
write_verilog $netlist
```

But when I try to do the similar thing in the tcl script file, it cannot identify the read_systemverilog command.
Here is my tcl script. I add `yosys -import`  to support yosys command in tcl file. And I run `yosys -c tcl_script_file`
```
yosys -import
plugin -i systemverilog
read_systemverilog $file
synth -top $top_module
write_verilog $netlist
```

The output log is shown below.

```
Yosys 0.16+65 (git sha1 52d8ddee0, gcc 12.1.0 -fPIC -Os)

[TCL: yosys -import] Command name collision: found pre-existing command `cd' -> skip.
[TCL: yosys -import] Command name collision: found pre-existing command `eval' -> skip.
[TCL: yosys -import] Command name collision: found pre-existing command `exec' -> skip.
[TCL: yosys -import] Command name collision: found pre-existing command `read' -> skip.
[TCL: yosys -import] Command name collision: found pre-existing command `trace' -> skip.
ERROR: TCL interpreter returned an error: invalid command name "read_systemverilog"
```

**Comment by minghungumich** [comment]
@rkapuscik @kgugala @hzeller @umarcor @tgorochowik @mithro @msaligane Now I can build the systemverilog plugin but I face issue with running those commands as a tcl script file.

**Comment by msaligane** [comment]
@minghungumich can you please add more description to this issue

**Comment by minghungumich** [comment]
@msaligane The issue has been updated.

**Comment by mithro** [comment]
@kgugala / @hzeller - Can you help figure out what is going on here and how the documentation needs to be updated so other people don't run into the same issue?

**Comment by rkapuscik** [comment]
This is caused by a somewhat counterintuitive way Yosys commands are added to tcl - and it affects every plugin. You need to re-import the commands after adding the plugin to gain access to them in tcl, like this:
```tcl
# Import base Yosys commands
yosys -import
# Load plugin(s)
plugin -i systemverilog
# Import commands added by the plugin
yosys -import
# Further steps...
read_systemverilog $file
```
You can also take a look at how it's done in the [tests](https://github.com/chipsalliance/yosys-f4pga-plugins/blob/main/systemverilog-plugin/tests/counter/counter.tcl) for the [plugins](https://github.com/chipsalliance/yosys-f4pga-plugins/blob/main/sdc-plugin/tests/pll/pll.tcl#L1-L3).

**Comment by minghungumich** [comment]
Thanks! That change works!
