### ISSUE TITLE
Plugin does not compile with current UHDM

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/yosys-f4pga-plugins#438]
In the latest UHDM, some enums have been renamed so that they will not clash with c++ 20 symbols

   * `vpiInterface` -> `vpiInterfaceInst`
   * `vpiModule` -> `vpiModuleInst`
   
(Note, in #436, I already prepared the code for some other aspect of current UHDM: to be ready to deal with the `std::string_view` return value of some fields)

**Comment by mglb** [comment]
Fixed. Yosys-systemverilog uses Surelog from 2 weeks ago, and dependabot PR with a bump passes in the CI.
