### ISSUE TITLE
Streaming operation unsupported

### ISSUE THREAD

**Issue by taylor-bsg** [chipsalliance/yosys-f4pga-plugins#442]
Per https://github.com/antmicro/yosys-systemverilog/issues/968

Not really sure about the relationship of this repo to that one

**Comment by mglb** [comment]
Fixed. The test https://github.com/jeras/UHDM-integration-tests/commit/87d736de151f3dd13ec360cfd1a793dba3cd2c56 (linked in https://github.com/antmicro/yosys-systemverilog/issues/968) currently passes formal verification.
